version: '3.8'

services:
 mysqldb:
  image: mysql
  build:
    context: .
    dockerfile: Dockerfile_SQL
  ports:
  - 3306:3306
  environment:
   MYSQL_DATABASE: urls_db
   MYSQL_USER: someuser
   MYSQL_PASSWORD: somepassword
   MYSQL_RANDOM_ROOT_PASSWORD: one
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  tty: true
  networks:
    mysqlnet:

 web:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
  - 80:80
  depends_on:
      - mysqldb
  restart: "on-failure"
  volumes:
  - ./:/app

volumes:
  mysql:
  mysql_config:

networks:
  mysqlnet:
    driver: bridge