version: '3.9'

services:
 db:
  image: postgres:latest
  container_name: db
  expose:
    - "5432"
  env_file:
    - .env
  volumes:
    - postrge_config:/usr/share/postgresql
    - ./sql_file/start.sql:/docker-entrypoint-initdb.d/start.sql
  networks:
    sqlnet:

 web:
  build:
   context: . #build the image for the web service from the dockerfile in parent directory
   dockerfile: Dockerfile
  ports:
  - 80:80
  depends_on:
      - db
  restart: "on-failure"
  links:
      - db 
  volumes:
  - ./:/app # map data & files from parent directory in host to microservice directory in docker container
  networks:
    sqlnet:

volumes:
  postrge_config:

networks:
  sqlnet:
    driver: bridge