version: '3.8'

services:
 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=weakroots1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

 web:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
  - 80:80
  depends_on:
      - mysqldb
  restart: "on-failure"
  volumes:
  - ./:/app

volumes:
  mysql:
  mysql_config: